language: node_js

node_js:
  - 8

after_success:
  - yarn spago run

deploy:
  github_token: $GITHUB_TOKEN
  local_dir: dist
  provider: pages
  skip_cleanup: true
  target_branch: master
  on:
    branch: develop

cache:
  directories:
    - $HOME/.cache/spago
    - .spago
    - output
