declare module 'mdast-util-to-hast/lib/all'
declare module 'rehype-autolink-headings'
declare module 'rehype-highlight'
declare module 'rehype-slug'
declare module 'retext'
declare module 'retext-smartypants'
